# Axon Configuration
axon.axonserver.servers=axon-server:8124

# Postgresql
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Web3
web3.provider=${WEB3_PROVIDER}
contract.address=${CONTRACT_ADDRESS}
private.key=${PRIVATE_KEY}

# Spring RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.rabbitmq.virtual-host=/

# RabbitMQ Management
rabbit.mgmt.host=http://rabbitmq:15672
rabbit.mgmt.user=${RABBITMQ_DEFAULT_USER}
rabbit.mgmt.pass=${RABBITMQ_DEFAULT_PASS}
rabbit.mgmt.vhost=/

# Force logging to console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.ict.um.orders=DEBUG

# ML
ml.model-path=classpath:models/xgb-model.bin

# Routing strategy
# routing.strategy=rule-based
# routing.strategy=ml
routing.strategy=training

# Training path
training.data-path=/app/data/training-data.csv
